name: Build and Release GUI (Linux)

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-gui-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Linux executable
        run: |
          pyinstaller --onefile src/application/main.py \
            --hidden-import=matplotlib.backends.backend_svg \
            --hidden-import=PIL._tkinter_finder \
            --paths=.
          mv dist/main dist/main-linux

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gui-executable-linux
          path: dist/main-linux

  release-gui-linux:
    needs: build-gui-linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Delete Previous Linux Release
        run: |
          gh release list --limit 100 | grep "^linux-" | awk '{print $1}' | while read tag; do
            echo "Deleting release $tag"
            gh release delete "$tag" --yes --cleanup-tag || true
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: gui-executable-linux
          path: .

      - name: Create Linux Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Linux Release ${{ github.sha }}"
          tag_name: "linux-${{ github.sha }}"
          files: main-linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
